### ISSUE TITLE
1.20.1 Support?

### ISSUE THREAD

**Issue by mxnmnm** [rune-scape/end_portal_parallax#2]
Can we get 1.20.1 support? Will we also get a forge/neoforge version for 1.20.1 (or at least making sure it's compatible with sinytra connector)?

**Comment by rune-scape** [comment]
done :) idk know the difference between forge and neoforged but it seems like a fork related to some drama with Lex,, idk, i used neoforged

**Comment by mxnmnm** [comment]
YAY, neoforge is the one people are using because it's literally the entire forge team except for lex so it seems to be getting the most adoption. Either way works for 1.20.1 tho :) (I'll close the issue when it gets approved on curseforge)

**Comment by mxnmnm** [comment]
Maybe posting on modrinth as well might not be a bad idea

**Comment by mxnmnm** [comment]
ummmm you made it for 1.20.4 not 1.20.1, can 1.20.1 happen or nah?

**Comment by mxnmnm** [comment]
It should be relatively similar to 1.19.4 because I tweaked the versions it allowed and I was able to enter a world but I unsurprisingly crashed when looking at the end portal so hopefully an update to that should be relatively simple.

**Comment by mxnmnm** [comment]
So I just tweaked the fabric.mod.json in the fabric version to be compatible for 1.20.1 and fabric 0.15.0 and it literally booted up with sinytra connector just fine lmao

**Comment by mxnmnm** [comment]
it should be really really really easy to just do that and port it to the fabric version at least so it can sync especially because if someone is on forge they can just use sinytra connector lol

**Comment by rune-scape** [comment]
oki so i cannot make a neoforged version of 1.20.1 bc the earliest mdk is 1.20.2,,
but yea i can try to go back and widen the version ranges for both fabric and forge,, i have to add a bugfix to all of them anyway :/ , found a bug thats probly causing alot of issues

**Comment by mxnmnm** [comment]
I'd recommend you use Forge 47.1.3 as this is when the split between forge and neoforge happened and for the most part neoforge is compatible with forge for 1.20.1 but forge versions after this might have issues so a lot of the mods stick to this version.

**Comment by rune-scape** [comment]
oki, you are wise, i will make a forge 1.20.1 version too

**Comment by mxnmnm** [comment]
yay ty

**Comment by IdrisQe** [comment]
Hi, I don't mean to be a bother but any news on this? 1.20.1 is, at least for now, the "main modding version" as far as I can tell, with many major mods sticking to it, probably until 1.21 or last release of 1.20 (thanks Mojang for the new confusing release scheme where minor versions have just as many breaking changes as major versions), so the lack of this mod is really unfortunate, as someone who's been annoyed by the crummy screenspace texture since it first replaced the amazing parallax.

**Comment by rune-scape** [comment]
oops i forgor

**Comment by rune-scape** [comment]
its up on curseforge :)
